### ISSUE TITLE
Soft Crash whenever attempting an autocrafting order from an Arcane Crafting Terminal #410

### ISSUE THREAD

**Issue by xJon** [Delfayne/ThaumicEnergistics#30] opened 2024-05-03 14:58 UTC
Reposted from https://github.com/Nividica/ThaumicEnergistics/issues/410:
> Bug Desctiption: Whenever I attempt to put through an autocrafting order from an arcane crafting terminal, my game soft crashes. The prompt to select the number of items to autocraft pops up, but when I hit next, the game soft crashes before the next prompt showing the items to be crafted shows up.
> 
> Steps to reproduce the behavior:
> 
> 1. Open arcane crafting terminal
> 2. Select an item to autocraft
> 3. select any quantity and hit next
> 4. Game then soft crashes
> 
> **Expected behavior** The next prompt showing the "items to be crafted" and then clicking the start button.
> 
> **Screenshots** ![2024-04-18_20 29 18](https://private-user-images.githubusercontent.com/144782216/323794488-b590262a-8f8e-45ce-ac49-380a594ed11c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDg1NTgsIm5iZiI6MTcxNDc0ODI1OCwicGF0aCI6Ii8xNDQ3ODIyMTYvMzIzNzk0NDg4LWI1OTAyNjJhLThmOGUtNDVjZS1hYzQ5LTM4MGE1OTRlZDExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxNDU3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGNhYmM3ODc3OWNkM2EyM2M4YmFjN2ZjM2IxM2I1MWFiNDMyYjQyODA0MjY5OTM3NTA5ODQ1MzA3MWU5YTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zfXrVGl42J-uV4XlgyfyNlCILM2YALJy1MtDVEL28Nw) ![2024-04-18_20 29 22](https://private-user-images.githubusercontent.com/144782216/323794526-af4aa02e-1afc-4f72-9d54-6cb2c75de6b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDg1NTgsIm5iZiI6MTcxNDc0ODI1OCwicGF0aCI6Ii8xNDQ3ODIyMTYvMzIzNzk0NTI2LWFmNGFhMDJlLTFhZmMtNGY3Mi05ZDU0LTZjYjJjNzVkZTZiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxNDU3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmY3MTFlY2NiMDIzNzEyZjdiM2ZjMGJkN2Q3MGExMGYzMDA5NzVhOTQ2ZDgxYWQ0OTUzYTFmZTNjNDU3ZTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0nlcVJIOZ57LTUUZcVDJXMr9UtG4qqp_BaO2fRMsGXk) ![2024-04-18_20 29 33](https://private-user-images.githubusercontent.com/144782216/323794542-2015668c-8e22-43de-bd4a-c94e100ac370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDg1NTgsIm5iZiI6MTcxNDc0ODI1OCwicGF0aCI6Ii8xNDQ3ODIyMTYvMzIzNzk0NTQyLTIwMTU2NjhjLThlMjItNDNkZS1iZDRhLWM5NGUxMDBhYzM3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxNDU3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGQwMGI0ZTkwNmNiMjYxMjQ5OTllM2ZmY2I4YjMzOWFjM2RhMGQyYjZjY2FiMmQ5ZDc3YzJhZmNkODNhZDU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vKrugJEfzlLQ9C3X9EjADPkime9t38XNKLSGLRSuWe8)
> 
> **Version Information**
> 
> * Minecraft: 1.12.2
> * Forge: 8.0.99.99
> * Applied Energistics: AE2 Unofficial Extended Life v0.56.4
> * Thaumcraft: 6.1.BETA26
> * Thaumic Energistics: 2.2.7
> * Modpack: The 1.12.2 Pack
> 
> **Logs/Crashlogs** https://mclo.gs/Y2XPEgT

**Comment by Delfayne** [comment] 2024-05-08 22:58
There's been a few posts on this from the DJ2 discord also, and your crash log matches theirs. 

I remain uncertain why this behaviour occurs. When the gui is initialised, we get the number box from the AE2 gui via reflection and hold onto it, later trying to get the craft quantity when you click next.

The code already tries to fail early if it cannot get the number box at initialisation time. I don't know why it nulls out when we click next, I have been unable to reproduce it.

However I have rewritten all the code around this area, removed the reflection and instead deferred accessing any element of the AE2 gui until as late as possible. Hopefully by this point, everything is initialised fully. It may help.

**Comment by xJon** [comment] 2024-05-09 00:52
@Delfayne If you have a test build to share, I can send it to the player who reported the issue to confirm whether it still occurs.

**Comment by zeng-github01** [comment] 2024-05-09 06:54
> @Delfayne If you have a test build to share, I can send it to the player who reported the issue to confirm whether it still occurs.
[FixBuild.zip](https://github.com/Delfayne/ThaumicEnergistics/files/15258685/FixBuild.zip)

Here is the fix build, containing the mod files for GalactiCraft and ThaumicEnergistics

**Comment by Delfayne** [comment] 2024-05-10 04:58
https://github.com/Delfayne/ThaumicEnergistics/releases/tag/v2.3.0
@xJon @zeng-github01 
You can find a pre-release version here, I will push out to CF at the weekend if testing goes well.

**Comment by Delfayne** [comment] 2024-05-10 05:23
Fixed in https://github.com/Delfayne/ThaumicEnergistics/releases/tag/v2.3.0

**Closed by Delfayne** 2024-05-10 05:23 UTC
Labels: bug

**Comment by xJon** [comment] 2024-05-29 14:40
@Delfayne Any reason `2.3.0` is not uploaded to CurseForge?

**Comment by Delfayne** [comment] 2024-05-29 22:10
> @Delfayne Any reason `2.3.0` is not uploaded to CurseForge?

Some concerns were raised when some DJ2 players imported the mod and it behaved strangely for them. It's an isolated report, but I wasn't sure if there was a bigger problem.

Have you tested 2.3.0 without issues?

**Comment by xJon** [comment] 2024-05-29 22:16
@Delfayne Not yet tested, but I will report soon if I encounter any issues 👍
